*&---------------------------------------------------------------------*
*& Include          ZSYR1580_NAMDV_F01
*&---------------------------------------------------------------------*
FORM GET_SFLIGHT_DATA.
  SELECT SINGLE CARRID
  INTO @DATA(LV_CARRID)
  FROM ZY052T
  WHERE CARRID = @P_CARRID.

  IF SY-SUBRC <> 0.
    MESSAGE TEXT-E01 TYPE 'E'.
    LEAVE TO SCREEN 0.
  ENDIF.

  CALL FUNCTION 'ZFM_GET_SFLIGHT_DATA_T16_NAMDV'
   EXPORTING
    IV_CARRID           = P_CARRID
    IT_CONNID           = S_CONNID[]
  IMPORTING
    ET_SFLIGHT          = GT_SFLIGHT_DATA
  EXCEPTIONS
    OTHERS              = 2.

  IF SY-SUBRC <> 0.
    MESSAGE TEXT-E02 TYPE 'E'.
    LEAVE TO SCREEN 0.
  ENDIF.
ENDFORM.

FORM DISPLAY_SFLIGHT_DATA.
  WRITE: /     TEXT-001,
           15  TEXT-002,
           30  TEXT-003,
           45  TEXT-004,
           72  TEXT-005,
           90  TEXT-006,
           115 TEXT-007,
           140 TEXT-008.

  WRITE: / SY-ULINE.

  LOOP AT GT_SFLIGHT_DATA INTO DATA(LS_SFLIGHT).
    WRITE: /     LS_SFLIGHT-CARRID,
             15  LS_SFLIGHT-CARRNAME,
             30  LS_SFLIGHT-CONNID,
             45  LS_SFLIGHT-FLDATE,
             60  LS_SFLIGHT-PRICE CURRENCY LS_SFLIGHT-CURRENCY,
             90  LS_SFLIGHT-VAC_SEATS,
             115 LS_SFLIGHT-VAC_SEATS_B,
             140 LS_SFLIGHT-VAC_SEATS_F.
  ENDLOOP.
ENDFORM.

FORM DISPLAY_PRICES_WHEN_GROUP_BY.
  DATA: LV_SUM_PRICE TYPE ZY052T-PRICE,
        LV_CURRENCY  TYPE ZY052T-CURRENCY.

  WRITE: /    TEXT-001,
           15 TEXT-009,
           30 TEXT-010.

  WRITE: / SY-ULINE.

  LOOP AT GT_SFLIGHT_DATA INTO DATA(LS_SFLIGHT)
    GROUP BY ( CARRID = LS_SFLIGHT-CARRID CONNID = LS_SFLIGHT-CONNID )
    ASCENDING
    ASSIGNING FIELD-SYMBOL(<GROUP>).

    LV_SUM_PRICE = 0.
    LV_CURRENCY = LS_SFLIGHT-CURRENCY.

    LOOP AT GROUP <GROUP> INTO DATA(LS_GROUP).
      LV_SUM_PRICE = LS_GROUP-PRICE + LV_SUM_PRICE.
    ENDLOOP.

    WRITE: /    <GROUP>-CARRID,
             15 <GROUP>-CONNID,
             30 LV_SUM_PRICE CURRENCY LV_CURRENCY.
  ENDLOOP.

  WRITE: / SY-ULINE.
ENDFORM.