*&---------------------------------------------------------------------*
*& Report ZSYR1412_T2_OOP_NAMDV
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZSYR1412_T2_OOP_NAMDV.

TABLES: ZY052T.

* DEFINITION CLASS FLIGHT DATA
CLASS ZCL_FLIGHT_DATA DEFINITION.
  PUBLIC SECTION.
    TYPES: GT_SFLIGHT TYPE ZTT_SFLIGHT_NAMDV.

    METHODS: CONSTRUCTOR IMPORTING IV_CARRID TYPE ZY052T-CARRID
                                   IT_CONNID TYPE ZTT_CONNID_NAMDV,
             VALIDATE_CARRID,
             GET_SFLIGHT_DATA,
             DISPLAY_SFLIGHT_DATA,
             DISPLAY_GROUP_PRICES.

  PRIVATE SECTION.
    DATA: PRV_CARRID     TYPE ZY052T-CARRID,
          PRT_CONNID     TYPE ZTT_CONNID_NAMDV,
          PRT_SFLIGHT    TYPE GT_SFLIGHT.
ENDCLASS.

* IMPLEMENTATION CLASS FLIGHT DATA
CLASS ZCL_FLIGHT_DATA IMPLEMENTATION.
  METHOD CONSTRUCTOR.
    PRV_CARRID = IV_CARRID.
    PRT_CONNID = IT_CONNID.
  ENDMETHOD.

  METHOD VALIDATE_CARRID.
    SELECT
    SINGLE CARRID
    FROM ZY052T
    WHERE CARRID = @PRV_CARRID
    INTO @DATA(LV_CARRID).

    IF SY-SUBRC <> 0.
      MESSAGE 'AIRLINE CODE DOES NOT EXIST.' TYPE 'E'.
    ENDIF.
  ENDMETHOD.

  METHOD GET_SFLIGHT_DATA.
    SELECT
        CONNID,
        FLDATE,
        PRICE,
        CURRENCY,
        SEATSMAX,
        SEATSOCC,
        SEATSMAX_B,
        SEATSOCC_B,
        SEATSMAX_F,
        SEATSOCC_F,
        SFLIGHT~CARRID,
        SCARR~CARRNAME
    FROM ZY052T AS SFLIGHT
    JOIN ZY050T AS SCARR
      ON SCARR~CARRID = SFLIGHT~CARRID
    INTO CORRESPONDING FIELDS OF TABLE @PRT_SFLIGHT
    WHERE SFLIGHT~CARRID = @PRV_CARRID AND SFLIGHT~CONNID IN @PRT_CONNID.

    IF SY-SUBRC <> 0.
      MESSAGE 'NO DATA.' TYPE 'I'.
    ENDIF.

    CALL FUNCTION 'ZFM_GET_SFLIGHT_DATA_T16_NAMDV'
      EXPORTING
        IV_CARRID  = PRV_CARRID
        IT_CONNID  = PRT_CONNID
      IMPORTING
        ET_SFLIGHT = PRT_SFLIGHT
      EXCEPTIONS
        OTHERS        = 2.

    IF SY-SUBRC <> 0.
      MESSAGE 'NO DATA' TYPE 'I'.
    ENDIF.
  ENDMETHOD.

  METHOD DISPLAY_SFLIGHT_DATA.
    DATA: LV_VACANT_SEATS_ECONOMY  TYPE I,
          LV_VACANT_SEATS_BUSINESS TYPE I,
          LV_VACANT_SEATS_FIRST    TYPE I.

    WRITE: / 'AIRLINE CODE',
             15 'AIRLINE NAME',
             30 'FLIGHT NO.',
             45 'FLIGHT DATE',
             72 'PRICE',
             90 'VACANT SEAT (ECONOMY)',
             115 'VACANT SEAT (BUSINESS)',
             140 'VACANT SEAT (FIRST)'.
    WRITE: / SY-ULINE.

    LOOP AT PRT_SFLIGHT INTO DATA(LS_SFLIGHT).
      LV_VACANT_SEATS_ECONOMY  = LS_SFLIGHT-SEATSMAX   - LS_SFLIGHT-SEATSOCC.
      LV_VACANT_SEATS_BUSINESS = LS_SFLIGHT-SEATSMAX_B - LS_SFLIGHT-SEATSOCC_B.
      LV_VACANT_SEATS_FIRST    = LS_SFLIGHT-SEATSMAX_F - LS_SFLIGHT-SEATSOCC_F.

      WRITE: / LS_SFLIGHT-CARRID,
               15  LS_SFLIGHT-CARRNAME,
               30  LS_SFLIGHT-CONNID,
               45  LS_SFLIGHT-FLDATE,
               60  LS_SFLIGHT-PRICE CURRENCY LS_SFLIGHT-CURRENCY,
               90  LV_VACANT_SEATS_ECONOMY,
               115 LV_VACANT_SEATS_BUSINESS,
               140 LV_VACANT_SEATS_FIRST.
    ENDLOOP.
  ENDMETHOD.

  METHOD DISPLAY_GROUP_PRICES.
    DATA: LV_SUM_PRICE TYPE ZY052T-PRICE,
          LV_CURRENCY  TYPE ZY052T-CURRENCY.

    WRITE: / 'AIRLINE CODE',
             15 'FLIGHT NUMBER',
             30 'TOTAL PRICE'.
    WRITE: / SY-ULINE.

    LOOP AT PRT_SFLIGHT INTO DATA(LS_SFLIGHT)
      GROUP BY ( CARRID = LS_SFLIGHT-CARRID CONNID = LS_SFLIGHT-CONNID )
      ASCENDING
      ASSIGNING FIELD-SYMBOL(<GROUP>).

      LV_SUM_PRICE = 0.
      LV_CURRENCY = LS_SFLIGHT-CURRENCY.

      LOOP AT GROUP <GROUP> INTO DATA(LS_GROUP).
        LV_SUM_PRICE = LV_SUM_PRICE + LS_GROUP-PRICE.
      ENDLOOP.

      WRITE: / <GROUP>-CARRID,
               15 <GROUP>-CONNID,
               20 LV_SUM_PRICE CURRENCY LV_CURRENCY.
    ENDLOOP.

    WRITE: / SY-ULINE.
  ENDMETHOD.
ENDCLASS.

DATA: GO_FLIGHT_DATA TYPE REF TO ZCL_FLIGHT_DATA.

PARAMETERS: P_CARRID TYPE ZY052T-CARRID OBLIGATORY.
SELECT-OPTIONS: S_CONNID FOR ZY052T-CONNID.

START-OF-SELECTION.
  CREATE OBJECT GO_FLIGHT_DATA
    EXPORTING
      IV_CARRID = P_CARRID
      IT_CONNID = S_CONNID[].

  GO_FLIGHT_DATA->VALIDATE_CARRID( ).
  GO_FLIGHT_DATA->GET_SFLIGHT_DATA( ).
  GO_FLIGHT_DATA->DISPLAY_SFLIGHT_DATA( ).
  GO_FLIGHT_DATA->DISPLAY_GROUP_PRICES( ).