*&---------------------------------------------------------------------*
*& Report ZSYR1460_NAMDV
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZSYR1460_NAMDV.

" TASK 1 WRITE AN EXECUTABLE PROGRAM THAT PERFORMS THE FOLLOWING CALCULATION: 2 + 3 * 5.
FORM TASK1.
  DATA: RESULT TYPE i.
  RESULT = 2 + 3 * 5.
  WRITE: / 'Output:', RESULT.
ENDFORM.

" TASK 2 WRITE AN EXECUTABLE PROGRAM THAT GETS TWO INTEGERS AND PERFORMS CALCULATIONS.
FORM TASK2.
  DATA: NUM1           TYPE I VALUE 10,
        NUM2           TYPE I VALUE 5,
        ADDITION       TYPE I,
        SUBTRACTION    TYPE I,
        MULTIPLICATION TYPE I,
        DIVISION       TYPE I,
        POWER          TYPE I.

  ADDITION = NUM1 + NUM2.
  SUBTRACTION = NUM1 - NUM2.
  MULTIPLICATION = NUM1 * NUM2.
  DIVISION = NUM1 / NUM2.
  POWER = NUM1 ** NUM2.

  WRITE: / 'ADDITION:', ADDITION,
         / 'SUBTRACTION:', SUBTRACTION,
         / 'MULTIPLICATION:', MULTIPLICATION,
         / 'DIVISION:', DIVISION,
         / 'POWER:', POWER.
ENDFORM.

" TASK 3 WRITE AN EXECUTABLE PROGRAM THAT GETS TWO INTEGERS VIA PARAMETERS AND PERFORMS CALCULATIONS.
SELECTION-SCREEN BEGIN OF BLOCK BT03 WITH FRAME TITLE TEXT-B03.
PARAMETERS: P_NUM1 TYPE I, P_NUM2 TYPE I.
SELECTION-SCREEN END OF BLOCK BT03.

FORM TASK3 USING U_NUM1 TYPE I
                 U_NUM2 TYPE I.
  DATA: ADDITION       TYPE I,
        SUBTRACTION    TYPE I,
        MULTIPLICATION TYPE I,
        DIVISION       TYPE I,
        POWER          TYPE I.

  IF U_NUM1 IS INITIAL OR U_NUM2 IS INITIAL.
    RETURN.
  ENDIF.

  ADDITION = U_NUM1 + U_NUM2.
  SUBTRACTION = U_NUM1 - U_NUM2.
  MULTIPLICATION = U_NUM1 * U_NUM2.

  IF U_NUM2 NE 0.
    DIVISION = U_NUM1 / U_NUM2.
  ELSE.
    DIVISION = 0.
  ENDIF.
  POWER = P_NUM1 ** P_NUM2.

  WRITE: / 'ADDITION:', ADDITION,
         / 'SUBTRACTION:', SUBTRACTION,
         / 'MULTIPLICATION:', MULTIPLICATION,
         / 'DIVISION:', DIVISION,
         / 'POWER:', POWER.
ENDFORM.

" TASK 4 WRITE AN EXECUTABLE PROGRAM THAT CONCATENATES TWO WORDS AND WRITES THE RESULT.
FORM TASK4.
  DATA: WORD1        TYPE STRING VALUE 'HELLO',
        WORD2        TYPE STRING VALUE 'WORLD',
        CONCATENATED TYPE STRING.

  CONCATENATE WORD1 WORD2 INTO CONCATENATED SEPARATED BY SPACE.
  WRITE: / 'OUTPUT:', CONCATENATED.
ENDFORM.

" TASK 5 WRITE AN EXECUTABLE PROGRAM THAT CONCATENATES TWO WORDS AND THE CURRENT MONTH.
FORM TASK5.
  DATA: WORD1  TYPE STRING VALUE 'HELLO',
        WORD2  TYPE STRING VALUE 'WORLD',
        MONTH  TYPE STRING,
        RESULT TYPE STRING.

  MONTH = SY-DATUM+4(2).
  RESULT = |{ WORD1 }-{ WORD2 }-{ MONTH }|.
  WRITE: / RESULT.
ENDFORM.

" TASK 6 WRITE AN EXECUTABLE PROGRAM THAT READS THE CURRENT SYSTEM DATE AND WRITES IT IN TEXT FORMAT.
FORM TASK6.
  DATA: LV_DAY      TYPE STRING,
        LV_MONTH    TYPE STRING,
        LV_YEAR     TYPE STRING,
        LV_MONTH_S  TYPE T247,
        LS_DATE     TYPE STRING.

  CALL FUNCTION 'IDWT_READ_MONTH_TEXT'
    EXPORTING
      LANGU = SY-LANGU
      MONTH = SY-DATUM+4(2)
    IMPORTING
      T247  = LV_MONTH_S.
  LV_MONTH = LV_MONTH_S-LTX.

* HANDLE DAY
  IF SY-DATUM+6(2) = '01'.
    LV_DAY = 'FIRST'.
  ELSEIF SY-DATUM+6(2) = '02'.
    LV_DAY = 'SECOND'.
  ELSEIF SY-DATUM+6(2) = '03'.
    LV_DAY = 'THIRD'.
  ELSE.
    IF SY-DATUM+6(2) BETWEEN 04 AND 19.
      CASE SY-DATUM+6(2).
        WHEN '04'. LV_DAY = 'FOURTH'.
        WHEN '05'. LV_DAY = 'FIFTH'.
        WHEN '06'. LV_DAY = 'SIXTH'.
        WHEN '07'. LV_DAY = 'SEVENTH'.
        WHEN '08'. LV_DAY = 'EIGHTH'.
        WHEN '09'. LV_DAY = 'NINTH'.
        WHEN '10'. LV_DAY = 'TENTH'.
        WHEN '11'. LV_DAY = 'ELEVENTH'.
        WHEN '12'. LV_DAY = 'TWELFTH'.
        WHEN '13'. LV_DAY = 'THIRTEENTH'.
        WHEN '14'. LV_DAY = 'FOURTEENTH'.
        WHEN '15'. LV_DAY = 'FIFTEENTH'.
        WHEN '16'. LV_DAY = 'SIXTEENTH'.
        WHEN '17'. LV_DAY = 'SEVENTEENTH'.
        WHEN '18'. LV_DAY = 'EIGHTEENTH'.
        WHEN '19'. LV_DAY = 'NINETEENTH'.
      ENDCASE.
      CONCATENATE LV_DAY 'TH' INTO LV_DAY.
    ELSE.
      CASE SY-DATUM+6(2).
        WHEN '20'. LV_DAY = 'TWENTIETH'.
        WHEN '21'. LV_DAY = 'TWENTY-FIRST'.
        WHEN '22'. LV_DAY = 'TWENTY-SECOND'.
        WHEN '23'. LV_DAY = 'TWENTY-THIRD'.
        WHEN '24'. LV_DAY = 'TWENTY-FOURTH'.
        WHEN '25'. LV_DAY = 'TWENTY-FIFTH'.
        WHEN '26'. LV_DAY = 'TWENTY-SIXTH'.
        WHEN '27'. LV_DAY = 'TWENTY-SEVENTH'.
        WHEN '28'. LV_DAY = 'TWENTY-EIGHTH'.
        WHEN '29'. LV_DAY = 'TWENTY-NINTH'.
        WHEN '30'. LV_DAY = 'THIRTIETH'.
        WHEN '31'. LV_DAY = 'THIRTY-FIRST'.
      ENDCASE.
    ENDIF.
  ENDIF.

* HANDLE YEAR
  LV_YEAR = SY-DATUM(4).

* PRINT RESULT
  WRITE: /'OUTPUT:', LV_MONTH, ' THE ', LV_DAY, ', ', LV_YEAR. NEW-LINE.
ENDFORM.

" TASK 7 WRITE AN EXECUTABLE PROGRAM THAT READS THE CURRENT SYSTEM TIME AND WRITES THE TIME IN 6 DIFFERENT ZONES.
FORM TASK7.
  DATA LV_TIMEZONE1        TYPE TZNZONE VALUE 'GMTUK'.
  DATA LV_TIMEZONE2        TYPE TZNZONE VALUE 'INDIA'.
  DATA LV_TIMEZONE3        TYPE TZNZONE VALUE 'BRAZIL'.
  DATA LV_TIMEZONE4        TYPE TZNZONE VALUE 'CST'.
  DATA LV_TIMEZONE5        TYPE TZNZONE VALUE 'ISRAEL'.
  DATA LV_TIMEZONE6        TYPE TZNZONE VALUE 'RUS06'.
  DATA LV_TIMESTAMP        TYPE TZONREF-TSTAMPS.
  DATA LV_TIMESTAMP_STRING TYPE STRING.

  CONCATENATE SY-DATUM SY-UZEIT INTO LV_TIMESTAMP_STRING.
  LV_TIMESTAMP = LV_TIMESTAMP_STRING.

  WRITE: / LV_TIMEZONE1, ':', LV_TIMESTAMP TIME ZONE LV_TIMEZONE1. NEW-LINE.
  WRITE: / LV_TIMEZONE2, ':', LV_TIMESTAMP TIME ZONE LV_TIMEZONE2. NEW-LINE.
  WRITE: / LV_TIMEZONE3, ':', LV_TIMESTAMP TIME ZONE LV_TIMEZONE3. NEW-LINE.
  WRITE: / LV_TIMEZONE4, ':', LV_TIMESTAMP TIME ZONE LV_TIMEZONE4. NEW-LINE.
  WRITE: / LV_TIMEZONE5, ':', LV_TIMESTAMP TIME ZONE LV_TIMEZONE5. NEW-LINE.
  WRITE: / LV_TIMEZONE6, ':', LV_TIMESTAMP TIME ZONE LV_TIMEZONE6. NEW-LINE.
ENDFORM.

" TASK 8 WRITE AN EXECUTABLE PROGRAM THAT COUNTS HOW MANY VOWELS ARE IN THE NAME OF THE USER.
FORM TASK8.
  DATA LV_VOWELS_COUNT TYPE I.
  DATA LV_USER LIKE SY-UNAME.

  LV_USER = SY-UNAME.

  TRANSLATE LV_USER TO UPPER CASE.

  FIND ALL OCCURRENCES OF REGEX 'A|E|I|O|U' IN LV_USER MATCH COUNT LV_VOWELS_COUNT.

  WRITE: / 'USER:', LV_USER.
  WRITE: / 'TOTAL VOWELS:', LV_VOWELS_COUNT.
ENDFORM.

" TASK 9 WRITE AN EXECUTABLE PROGRAM THAT COUNTS A STRING LENGTH AND IF IT'S BIGGER THAN 20 CHARACTERS.
FORM TASK9.
  DATA LV_STRING TYPE STRING VALUE '1234567890ABCDEFGHIJ21'.
  DATA LV_STRING_LENGTH TYPE I.
  LV_STRING_LENGTH = STRLEN( LV_STRING ).

  IF LV_STRING_LENGTH > 20.
    WRITE 'TOO BIG'.
  ELSE.
    WRITE LV_STRING_LENGTH.
  ENDIF.
ENDFORM.

" TASK 10 WRITE AN EXECUTABLE PROGRAM THAT COUNTS FROM 1 TO 100 AND FOR EACH MULTIPLE.
FORM TASK10.
  DATA LV_CURRENT_NUMBER TYPE I VALUE 1.

  WHILE LV_CURRENT_NUMBER <= 100.
    IF ( LV_CURRENT_NUMBER MOD 8 ) = 0.
      WRITE: 'THE NUMBER', LV_CURRENT_NUMBER, ' IS A MULTIPLE OF 8'.
      NEW-LINE.
    ENDIF.
    ADD 1 TO LV_CURRENT_NUMBER.
  ENDWHILE.
ENDFORM.

" TASK 11 WRITE AN EXECUTABLE PROGRAM THAT CONTAINS A ROUTINE WHICH PRINTS ALL USERNAMES IN THE SYSTEM.
TYPES GTT_USERS TYPE TABLE OF USR04-BNAME.

FORM TASK11.
  DATA LT_USERS TYPE GTT_USERS.
  SELECT BNAME
  FROM USR04
  INTO TABLE LT_USERS.
  PERFORM PRINT_USERS USING LT_USERS.
ENDFORM.

FORM PRINT_USERS USING U_LT_USERS TYPE GTT_USERS.
  DATA LS_USER TYPE LINE OF GTT_USERS.
  LOOP AT U_LT_USERS INTO LS_USER.
    WRITE LS_USER. NEW-LINE.
  ENDLOOP.
ENDFORM.

" TASK 12 PRINT THE CONTENTS OF ALL GLOBAL VARIABLES BEFORE THE ROUTINE IS CALLED.
DATA: GV_VAR1 TYPE I VALUE 5,
      GV_VAR2 TYPE I VALUE 10,
      GV_VAR3 TYPE I VALUE 15,
      GV_VAR4 TYPE I VALUE 20.

FORM TASK12.
  WRITE: /'BEFORE CALL FORM:'.
  WRITE: /'GV_VAR1:', GV_VAR1,
         /'GV_VAR2:', GV_VAR2,
         /'GV_VAR3:', GV_VAR3,
         /'GV_VAR4:', GV_VAR4.

  PERFORM HANDLE_VALUES_TASK_12 USING    GV_VAR1 GV_VAR2
                                CHANGING GV_VAR3 GV_VAR4.

  WRITE: /'AFTER CALLING FORM:'.
  WRITE: /'GV_VAR1:', GV_VAR1,
         /'GV_VAR2:', GV_VAR2,
         /'GV_VAR3:', GV_VAR3,
         /'GV_VAR4:', GV_VAR4.
  WRITE: / SY-ULINE.
ENDFORM.

FORM HANDLE_VALUES_TASK_12 USING    U_VAR1 TYPE I
                                    U_VAR2 TYPE I
                           CHANGING C_VAR3 TYPE I
                                    C_VAR4 TYPE I.

  WRITE: / 'AT THE BEGINNING OF FORM:'.
  WRITE: / 'GV_VAR1:', U_VAR1,
         / 'GV_VAR2:', U_VAR2,
         / 'GV_VAR3:', C_VAR3,
         / 'GV_VAR4:', C_VAR4.

  C_VAR3 = C_VAR3 + 20.
  C_VAR4 = C_VAR4 + 25.

  WRITE: / 'AT THE END OF FORM:'.
  WRITE: / 'GV_VAR1:', U_VAR1,
         / 'GV_VAR2:', U_VAR2,
         / 'GV_VAR3:', C_VAR3,
         / 'GV_VAR4:', C_VAR4.
ENDFORM.

* TASK 13
* 13. WRITE AN EXECUTABLE PROGRAM THAT HAS A ROUTINE THAT RECEIVES TWO NUMBERS.

DATA GV_LARGEST TYPE F.

FORM GET_LARGER
USING
  NUMBER_A TYPE F
  NUMBER_B TYPE F
CHANGING
  LARGEST_NUMBER TYPE F.

  IF NUMBER_A >= NUMBER_B.
    LARGEST_NUMBER = NUMBER_A.
  ELSE.
    LARGEST_NUMBER = NUMBER_B.
  ENDIF.
ENDFORM.

FORM TASK13.
  PERFORM GET_LARGER USING 1 2 CHANGING GV_LARGEST.
  WRITE GV_LARGEST EXPONENT 0. NEW-LINE.
  PERFORM GET_LARGER USING 4 3 CHANGING GV_LARGEST.
  WRITE GV_LARGEST EXPONENT 0. NEW-LINE.
  PERFORM GET_LARGER USING 5 5 CHANGING GV_LARGEST.
  WRITE GV_LARGEST EXPONENT 0. NEW-LINE.
  PERFORM GET_LARGER USING '6.2' '7.1' CHANGING GV_LARGEST.
  WRITE GV_LARGEST EXPONENT 0. NEW-LINE.
ENDFORM.

* TASK 14 WRITE AN EXECUTABLE PROGRAM THAT HAS A ROUTINE THAT RECEIVES TWO NUMBERS AND RETURNS A FLAG.

DATA GV_FLAG TYPE C.

FORM SET_FLAG_IF_EQUAL
USING
  NUMBER_A TYPE F
  NUMBER_B TYPE F
CHANGING
  FLAG TYPE C.

  IF NUMBER_A = NUMBER_B.
    FLAG = 'X'.
  ELSE.
    FLAG = ' '.
  ENDIF.
ENDFORM.

FORM TASK14.
  DATA: NUMBER_A TYPE F,
        NUMBER_B TYPE F.

  NUMBER_A = 1.
  NUMBER_B = 1.
  PERFORM SET_FLAG_IF_EQUAL USING NUMBER_A NUMBER_B CHANGING GV_FLAG.
  WRITE: / |A: { NUMBER_A }, B: { NUMBER_B }, FLAG: { GV_FLAG } |.

  NUMBER_A = 4.
  NUMBER_B = 3.
  PERFORM SET_FLAG_IF_EQUAL USING NUMBER_A NUMBER_B CHANGING GV_FLAG.
  WRITE: / |A: { NUMBER_A }, B: { NUMBER_B }, FLAG: { GV_FLAG } |.

  NUMBER_A = 5.
  NUMBER_B = 5.
  PERFORM SET_FLAG_IF_EQUAL USING NUMBER_A NUMBER_B CHANGING GV_FLAG.
  WRITE: / |A: { NUMBER_A }, B: { NUMBER_B }, FLAG: { GV_FLAG } |.

  NUMBER_A = '6.2'.
  NUMBER_B = '7.1'.
  PERFORM SET_FLAG_IF_EQUAL USING NUMBER_A NUMBER_B CHANGING GV_FLAG.
  WRITE: / |A: { NUMBER_A }, B: { NUMBER_B }, FLAG: { GV_FLAG } |.

ENDFORM.

* TASK 15 WRITE AN EXECUTABLE PROGRAM THAT HAS A ROUTINE THAT TAKES TWO NUMBERS AND WRITES.

DATA GV_RESULT TYPE F.

FORM DIVISION_OR_POWER2
USING
  NUMBER_A TYPE F
  NUMBER_B TYPE F
CHANGING
  RESULT TYPE F.

  DATA LV_NUMBER_EQUAL TYPE C.
  PERFORM SET_FLAG_IF_EQUAL
  USING
  NUMBER_A
  NUMBER_B
  CHANGING
  LV_NUMBER_EQUAL.
  IF LV_NUMBER_EQUAL = ABAP_TRUE.
    RESULT = NUMBER_A ** 2.
  ELSE.
    DATA LV_LARGER_NUMBER TYPE F.
    PERFORM GET_LARGER USING NUMBER_A NUMBER_B CHANGING LV_LARGER_NUMBER.
    IF NUMBER_A = LV_LARGER_NUMBER.
      RESULT = NUMBER_A / NUMBER_B.
    ELSE.
      RESULT = NUMBER_B / NUMBER_A.
    ENDIF.
  ENDIF.
  NEW-LINE.
ENDFORM.


FORM TASK15.
  DATA: NUMBER_A TYPE F,
        NUMBER_B TYPE F.

  NUMBER_A = 1.
  NUMBER_B = 1.
  PERFORM DIVISION_OR_POWER2
  USING NUMBER_A NUMBER_B
  CHANGING GV_RESULT.
  WRITE: / |A: { NUMBER_A }, B: { NUMBER_B }, GV_RESULT: { GV_RESULT } |.

  NUMBER_A = 3.
  NUMBER_B = 3.
  PERFORM DIVISION_OR_POWER2
  USING NUMBER_A NUMBER_B
  CHANGING GV_RESULT.
  WRITE: / |A: { NUMBER_A }, B: { NUMBER_B }, GV_RESULT: { GV_RESULT } |.

  NUMBER_A = 6.
  NUMBER_B = 2.
  PERFORM DIVISION_OR_POWER2
  USING NUMBER_A NUMBER_B
  CHANGING GV_RESULT.
  WRITE: / |A: { NUMBER_A }, B: { NUMBER_B }, GV_RESULT: { GV_RESULT } |.

  NUMBER_A = 2.
  NUMBER_B = 6.
  PERFORM DIVISION_OR_POWER2
  USING NUMBER_A NUMBER_B
  CHANGING GV_RESULT.
  WRITE: / |A: { NUMBER_A }, B: { NUMBER_B }, GV_RESULT: { GV_RESULT } |.

  NUMBER_A = 10.
  NUMBER_B = 2.
  PERFORM DIVISION_OR_POWER2
  USING NUMBER_A NUMBER_B
  CHANGING GV_RESULT.
  WRITE: / |A: { NUMBER_A }, B: { NUMBER_B }, GV_RESULT: { GV_RESULT } |.

  NUMBER_A = 2.
  NUMBER_B = 10.
  PERFORM DIVISION_OR_POWER2
  USING NUMBER_A NUMBER_B
  CHANGING GV_RESULT.
  WRITE: / |A: { NUMBER_A }, B: { NUMBER_B }, GV_RESULT: { GV_RESULT } |.
ENDFORM.

* TASK 16 WRITE AN EXECUTABLE PROGRAM THAT DOES NOT HAVE A ROUTINE. THE PROGRAM SHOULD.

TYPES: BEGIN OF TY_WORK_AREA_16,
         EMPLOYEE_ID   TYPE I,
         EMPLOYEE_NAME TYPE STRING,
         SALARY        TYPE P DECIMALS 2,
         HIRE_DATE     TYPE DATUM,
         DEPARTMENT    TYPE CHAR20,
       END OF TY_WORK_AREA_16.

DATA: GS_EMPLOYEE TYPE TY_WORK_AREA_16.

FORM TASK16.
  GS_EMPLOYEE-EMPLOYEE_ID = 1001.
  GS_EMPLOYEE-EMPLOYEE_NAME = 'JOHN DOE'.
  GS_EMPLOYEE-SALARY = '75000.50'.
  GS_EMPLOYEE-HIRE_DATE = '20230615'.
  GS_EMPLOYEE-DEPARTMENT = 'IT DEPARTMENT'.

  PERFORM DISPLAY_EMPLOYEE_INFO.
ENDFORM.

FORM DISPLAY_EMPLOYEE_INFO.
  WRITE: / 'EMPLOYEE ID:', GS_EMPLOYEE-EMPLOYEE_ID.
  WRITE: SY-ULINE.
  WRITE: / 'EMPLOYEE NAME:', GS_EMPLOYEE-EMPLOYEE_NAME.
  WRITE: SY-ULINE.
  WRITE: / 'SALARY:', GS_EMPLOYEE-SALARY.
  WRITE: SY-ULINE.
  WRITE: / 'HIRE DATE:', GS_EMPLOYEE-HIRE_DATE.
  WRITE: SY-ULINE.
  WRITE: / 'DEPARTMENT:', GS_EMPLOYEE-DEPARTMENT.
  WRITE: SY-ULINE.
ENDFORM.

* TASK 17 WRITE AN EXECUTABLE PROGRAM WITH A ROUTINE THAT RECEIVES A WORK AREA.
TYPES: BEGIN OF TY_MIXED_DATA_17,
         NUMBER TYPE I,
         TEXT   TYPE STRING,
         AMOUNT TYPE P DECIMALS 2,
         DATE   TYPE DATUM,
         FLAG   TYPE XFELD,
       END OF TY_MIXED_DATA_17.

DATA: GS_DATA_17        TYPE TY_MIXED_DATA_17,
      GV_EMPTY_COUNT_17 TYPE I.


FORM TASK17.
  GS_DATA_17-NUMBER = 0.
  GS_DATA_17-AMOUNT = '100.50'.
  GS_DATA_17-FLAG = ABAP_FALSE.
  PERFORM COUNT_UNFILLED_COMPONENTS
    CHANGING GS_DATA_17
             GV_EMPTY_COUNT_17.
  PERFORM DISPLAY_RESULT_17.
ENDFORM.

FORM COUNT_UNFILLED_COMPONENTS
  CHANGING PS_DATA     TYPE TY_MIXED_DATA_17
           PV_COUNT    TYPE I.

  PV_COUNT = 0.
  IF PS_DATA-NUMBER IS INITIAL.
    ADD 1 TO PV_COUNT.
  ENDIF.

  IF PS_DATA-TEXT IS INITIAL.
    ADD 1 TO PV_COUNT.
  ENDIF.

  IF PS_DATA-AMOUNT IS INITIAL.
    ADD 1 TO PV_COUNT.
  ENDIF.

  IF PS_DATA-DATE IS INITIAL.
    ADD 1 TO PV_COUNT.
  ENDIF.

  IF PS_DATA-FLAG IS INITIAL.
    ADD 1 TO PV_COUNT.
  ENDIF.
ENDFORM.

* ROUTINE TO DISPLAY THE RESULT
FORM DISPLAY_RESULT_17.
  WRITE: / 'NUMBER OF UNFILLED COMPONENTS:', GV_EMPTY_COUNT_17.
ENDFORM.

* TASK 18 WRITE AN EXECUTABLE PROGRAM WITH A ROUTINE THAT RECEIVES A WORK AREA.
TYPES: BEGIN OF TY_NUMERIC_DATA_18,
         INTEGER     TYPE I,
         PACKED_NUM  TYPE P DECIMALS 2,
         FLOAT_NUM   TYPE F,
         DECIMAL_NUM TYPE DECFLOAT16,
       END OF TY_NUMERIC_DATA_18.

DATA: GS_NUMERIC_DATA_18 TYPE TY_NUMERIC_DATA_18,
      GV_TOTAL_SUM_18    TYPE DECFLOAT34.

FORM TASK18.
  GS_NUMERIC_DATA_18-INTEGER = 100.
  GS_NUMERIC_DATA_18-PACKED_NUM = '250.75'.
  GS_NUMERIC_DATA_18-FLOAT_NUM = '75.5'.
  GS_NUMERIC_DATA_18-DECIMAL_NUM = '1234.56'.

  PERFORM SUM_NUMERIC_COMPONENTS
    CHANGING GS_NUMERIC_DATA_18
             GV_TOTAL_SUM_18.

  PERFORM DISPLAY_RESULT.

ENDFORM.

FORM SUM_NUMERIC_COMPONENTS
  CHANGING PS_NUMERIC_DATA TYPE TY_NUMERIC_DATA_18
           PV_SUM          TYPE DECFLOAT34.

  PV_SUM = 0.
  PV_SUM = PV_SUM + PS_NUMERIC_DATA-INTEGER.
  PV_SUM = PV_SUM + PS_NUMERIC_DATA-PACKED_NUM.
  PV_SUM = PV_SUM + PS_NUMERIC_DATA-FLOAT_NUM.
  PV_SUM = PV_SUM + PS_NUMERIC_DATA-DECIMAL_NUM.
ENDFORM.

" ROUTINE TO DISPLAY THE RESULT
FORM DISPLAY_RESULT.
  WRITE: / 'TOTAL SUM:', GV_TOTAL_SUM_18.

  WRITE: / 'BREAKDOWN:'.
  WRITE: / 'INTEGER:', GS_NUMERIC_DATA_18-INTEGER.
  WRITE: / 'PACKED NUMBER:', GS_NUMERIC_DATA_18-PACKED_NUM.
  WRITE: / 'FLOAT NUMBER:', GS_NUMERIC_DATA_18-FLOAT_NUM.
  WRITE: / 'DECIMAL NUMBER:', GS_NUMERIC_DATA_18-DECIMAL_NUM.
ENDFORM.

* TASK 19 WRITE AN EXECUTABLE PROGRAM WHICH HAS A ROUTINE THAT RECEIVES A WORK AREA WITH 3 CHAR.

TYPES: BEGIN OF TY_MIXED_DATA_19,
         CHAR1 TYPE CHAR20,
         CHAR2 TYPE CHAR20,
         CHAR3 TYPE CHAR20,
         NUM1  TYPE I,
         NUM2  TYPE P DECIMALS 2,
         NUM3  TYPE F,
       END OF TY_MIXED_DATA_19.

DATA: GS_DATA_19 TYPE TY_MIXED_DATA_19.

* MAIN PROGRAM LOGIC
FORM TASK19.
  GS_DATA_19-CHAR1 = 'HELL'.
  GS_DATA_19-CHAR2 = 'WORLD'.
  GS_DATA_19-CHAR3 = 'ABAP'.
  GS_DATA_19-NUM1 = 10.
  GS_DATA_19-NUM2 = '15.50'.
  GS_DATA_19-NUM3 = '20.5'.

  PERFORM PROCESS_COMPONENTS CHANGING GS_DATA_19.

  PERFORM DISPLAY_RESULTS.
ENDFORM.

* ROUTINE TO COUNT VOWELS USING REGEX
FORM COUNT_VOWELS
  USING    P_STRING    TYPE CHAR20
  CHANGING RV_COUNT    TYPE I.

  DATA: LV_STRING  TYPE STRING,
        LT_MATCHES TYPE MATCH_RESULT_TAB.

  LV_STRING = TO_UPPER( P_STRING ).

  FIND ALL OCCURRENCES OF REGEX '[AEIOU]'
    IN LV_STRING
    RESULTS LT_MATCHES.

  RV_COUNT = LINES( LT_MATCHES ).
ENDFORM.

* ROUTINE TO PROCESS AND CLEAR COMPONENTS BASED ON SPECIFIED RULES
FORM PROCESS_COMPONENTS
  CHANGING CS_DATA TYPE TY_MIXED_DATA_19.

  DATA: LV_NUMERIC_SUM  TYPE DECFLOAT34,
        LV_VOWEL_COUNT  TYPE I,
        LV_TOTAL_VOWELS TYPE I.

  LV_NUMERIC_SUM = ABS( CS_DATA-NUM1 ) +
                   ABS( TRUNC( CS_DATA-NUM2 ) ) +
                   ABS( TRUNC( CS_DATA-NUM3 ) ).

  CLEAR LV_TOTAL_VOWELS.

  PERFORM COUNT_VOWELS
    USING CS_DATA-CHAR1
    CHANGING LV_VOWEL_COUNT.
  ADD LV_VOWEL_COUNT TO LV_TOTAL_VOWELS.

  PERFORM COUNT_VOWELS
    USING CS_DATA-CHAR2
    CHANGING LV_VOWEL_COUNT.
  ADD LV_VOWEL_COUNT TO LV_TOTAL_VOWELS.

  PERFORM COUNT_VOWELS
    USING CS_DATA-CHAR3
    CHANGING LV_VOWEL_COUNT.
  ADD LV_VOWEL_COUNT TO LV_TOTAL_VOWELS.

  IF LV_NUMERIC_SUM MOD 2 = 1.
    CLEAR: CS_DATA-CHAR1,
           CS_DATA-CHAR2,
           CS_DATA-CHAR3.
  ENDIF.

  IF LV_TOTAL_VOWELS MOD 2 = 0.
    CLEAR: CS_DATA-NUM1,
           CS_DATA-NUM2,
           CS_DATA-NUM3.
  ENDIF.
ENDFORM.

* ROUTINE TO DISPLAY RESULTS
FORM DISPLAY_RESULTS.
  WRITE: / 'CHARACTER COMPONENTS:'.
  WRITE: / 'CHAR1:', GS_DATA_19-CHAR1.
  WRITE: / 'CHAR2:', GS_DATA_19-CHAR2.
  WRITE: / 'CHAR3:', GS_DATA_19-CHAR3.

  WRITE: / 'NUMERIC COMPONENTS:'.
  WRITE: / 'NUM1:', GS_DATA_19-NUM1.
  WRITE: / 'NUM2:', GS_DATA_19-NUM2.
  WRITE: / 'NUM3:', GS_DATA_19-NUM3.
ENDFORM.

* TASK 20 WRITE AN EXECUTABLE PROGRAM WHICH CONTAINS THREE INTERNAL TABLES (THEIR TYPE MUST CONTAIN

TYPES: BEGIN OF TY_LINE_20,
         ID    TYPE C LENGTH 10,
         NAME  TYPE STRING,
         VALUE TYPE I,
       END OF TY_LINE_20.

DATA IT_STANDARD TYPE STANDARD TABLE OF TY_LINE_20.
DATA IT_SORTED TYPE SORTED TABLE OF TY_LINE_20 WITH UNIQUE KEY ID.
DATA IT_HASHED TYPE HASHED TABLE OF TY_LINE_20 WITH UNIQUE KEY ID.

FORM TASK20.
  DATA WA TYPE TY_LINE_20.

  WA-ID = '3'.
  WA-NAME = 'JOHN'.
  WA-VALUE = 50.
  APPEND WA TO IT_STANDARD.
  INSERT WA INTO TABLE IT_SORTED.
  INSERT WA INTO TABLE IT_HASHED.

  WA-ID = '2'.
  WA-NAME = 'MARY'.
  WA-VALUE = 60.
  APPEND WA TO IT_STANDARD.
  INSERT WA INTO TABLE IT_SORTED.
  INSERT WA INTO TABLE IT_HASHED.

  WA-ID = '1'.
  WA-NAME = 'MAX'.
  WA-VALUE = 30.
  APPEND WA TO IT_STANDARD.
  INSERT WA INTO TABLE IT_SORTED.
  INSERT WA INTO TABLE IT_HASHED.

  WRITE: / 'CONTENTS OF STANDARD TABLE:'.
  LOOP AT IT_STANDARD INTO WA.
    WRITE: / WA-ID, WA-NAME, WA-VALUE.
  ENDLOOP.

  WRITE: / 'CONTENTS OF SORTED TABLE:'.
  LOOP AT IT_SORTED INTO WA.
    WRITE: / WA-ID, WA-NAME, WA-VALUE.
  ENDLOOP.

  WRITE: / 'CONTENTS OF HASHED TABLE:'.
  LOOP AT IT_HASHED INTO WA.
    WRITE: / WA-ID, WA-NAME, WA-VALUE.
  ENDLOOP.
ENDFORM.

* TASK 21 WRITE AN EXECUTABLE PROGRAM WHICH HAS A ROUTINE THAT RECEIVES AN INTERNAL TABLE.

TYPES: BEGIN OF TY_LINE_21,
         ID            TYPE C LENGTH 10,
         NAME          TYPE STRING,
         VALUE         TYPE I,
         CREATION_DATE TYPE D,
       END OF TY_LINE_21.

TYPES: TY_TABLE TYPE STANDARD TABLE OF TY_LINE_21 WITH DEFAULT KEY.

*ROUTINE TO COUNT INITIAL FIELDS IN A SINGLE LINE
FORM COUNT_LINE_INITIAL_FIELDS
  USING    IS_LINE         TYPE TY_LINE_21
  CHANGING CV_INITIAL_COUNT TYPE I.

  CV_INITIAL_COUNT = 0.

  IF IS_LINE-ID IS INITIAL.
    ADD 1 TO CV_INITIAL_COUNT.
  ENDIF.

  IF IS_LINE-NAME IS INITIAL.
    ADD 1 TO CV_INITIAL_COUNT.
  ENDIF.

  IF IS_LINE-VALUE IS INITIAL.
    ADD 1 TO CV_INITIAL_COUNT.
  ENDIF.

  IF IS_LINE-CREATION_DATE IS INITIAL.
    ADD 1 TO CV_INITIAL_COUNT.
  ENDIF.
ENDFORM.

*ROUTINE TO PROCESS ENTIRE TABLE AND DISPLAY INITIAL FIELD COUNTS
FORM PROCESS_TABLE_INITIAL_FIELDS
  USING    IT_INPUT_TABLE TYPE TY_TABLE.

  DATA: LV_LINE_INITIAL_COUNT  TYPE I,
        LV_TOTAL_INITIAL_COUNT TYPE I.

  LV_TOTAL_INITIAL_COUNT = 0.

  LOOP AT IT_INPUT_TABLE INTO DATA(LS_LINE).
    CLEAR LV_LINE_INITIAL_COUNT.

    PERFORM COUNT_LINE_INITIAL_FIELDS
      USING    LS_LINE
      CHANGING LV_LINE_INITIAL_COUNT.

    ADD LV_LINE_INITIAL_COUNT TO LV_TOTAL_INITIAL_COUNT.

    WRITE: / 'LINE', SY-TABIX,
             'INITIAL FIELDS:', LV_LINE_INITIAL_COUNT.
  ENDLOOP.

  NEW-LINE.
  WRITE: / 'TOTAL INITIAL FIELDS ACROSS ALL LINES:',
           LV_TOTAL_INITIAL_COUNT.
ENDFORM.

*MAIN PROGRAM EXECUTION
FORM TASK21.
  DATA: LT_DATA TYPE TY_TABLE.

  APPEND VALUE #(
    ID            = '1'
    NAME          = 'JOHN'
    VALUE         = 50
    CREATION_DATE = '20140727'
  ) TO LT_DATA.

  PERFORM PROCESS_TABLE_INITIAL_FIELDS USING LT_DATA.

  CLEAR LT_DATA.
  APPEND VALUE #(
    ID            = '2'
    NAME          = 'MARY'
    VALUE         = 20
  ) TO LT_DATA.

  PERFORM PROCESS_TABLE_INITIAL_FIELDS USING LT_DATA.

  CLEAR LT_DATA.
  APPEND VALUE #(
    ID            = '3'
    NAME          = 'MAX'
  ) TO LT_DATA.

  PERFORM PROCESS_TABLE_INITIAL_FIELDS USING LT_DATA.

  CLEAR LT_DATA.
  APPEND VALUE #(
  ) TO LT_DATA.

  PERFORM PROCESS_TABLE_INITIAL_FIELDS USING LT_DATA.
ENDFORM.

* TASK 22 WRITE AN EXECUTABLE PROGRAM WHICH HAS A ROUTINE THAT RECEIVES AN INTERNAL TABLE.
TYPES: BEGIN OF TY_LINE_22,
         ID            TYPE C LENGTH 10,
         NAME          TYPE STRING,
         VALUE         TYPE I,
         CREATION_DATE TYPE D,
       END OF TY_LINE_22.

TYPES: TY_TABLE_22 TYPE STANDARD TABLE OF TY_LINE_22 WITH DEFAULT KEY.

*ROUTINE TO COUNT BLANK FIELDS IN A SINGLE LINE
FORM COUNT_BLANK_FIELDS
  USING    IS_LINE         TYPE TY_LINE_22
  CHANGING CV_BLANK_COUNT   TYPE I.

  CV_BLANK_COUNT = 0.

  IF IS_LINE-ID IS INITIAL.
    ADD 1 TO CV_BLANK_COUNT.
  ENDIF.

  IF IS_LINE-NAME IS INITIAL.
    ADD 1 TO CV_BLANK_COUNT.
  ENDIF.

  IF IS_LINE-VALUE IS INITIAL.
    ADD 1 TO CV_BLANK_COUNT.
  ENDIF.

  IF IS_LINE-CREATION_DATE IS INITIAL.
    ADD 1 TO CV_BLANK_COUNT.
  ENDIF.
ENDFORM.

*ROUTINE TO PROCESS ENTIRE TABLE AND DISPLAY BLANK FIELD COUNTS
FORM PROCESS_TABLE_BLANK_FIELDS
  USING    IT_INPUT_TABLE TYPE TY_TABLE_22.

  DATA: LV_LINE_BLANK_COUNT  TYPE I,
        LV_TOTAL_BLANK_COUNT TYPE I.

  LV_TOTAL_BLANK_COUNT = 0.

  WRITE: / 'BLANK FIELDS ANALYSIS:'.
  ULINE.

  LOOP AT IT_INPUT_TABLE INTO DATA(LS_LINE).
    CLEAR LV_LINE_BLANK_COUNT.

    PERFORM COUNT_BLANK_FIELDS
      USING    LS_LINE
      CHANGING LV_LINE_BLANK_COUNT.

    WRITE: / 'LINE', SY-TABIX, '=>',
             LV_LINE_BLANK_COUNT, 'BLANK FIELDS'.

    ADD LV_LINE_BLANK_COUNT TO LV_TOTAL_BLANK_COUNT.
  ENDLOOP.

  ULINE.
  WRITE: / 'TOTAL:', LV_TOTAL_BLANK_COUNT, 'BLANK FIELDS'.
ENDFORM.


FORM TASK22.
  DATA: LT_TABLE_22 TYPE TY_TABLE_22.

  APPEND VALUE #(
    ID            = '1'
    NAME          = 'JOHN'
    VALUE         = 50
    CREATION_DATE = '20140727'
  ) TO LT_TABLE_22.

  PERFORM PROCESS_TABLE_BLANK_FIELDS USING LT_TABLE_22.

  CLEAR LT_TABLE_22.
  APPEND VALUE #(
    ID            = '2'
    NAME          = 'MARY'
    VALUE         = 20
  ) TO LT_TABLE_22.

  PERFORM PROCESS_TABLE_BLANK_FIELDS USING LT_TABLE_22.

  CLEAR LT_TABLE_22.
  APPEND VALUE #(
    ID            = '3'
    NAME          = 'MAX'
  ) TO LT_TABLE_22.

  PERFORM PROCESS_TABLE_BLANK_FIELDS USING LT_TABLE_22.

  CLEAR LT_TABLE_22.

  APPEND VALUE #(
  ) TO LT_TABLE_22.

  PERFORM PROCESS_TABLE_BLANK_FIELDS USING LT_TABLE_22.
ENDFORM.

* TASK 23 WRITE AN EXECUTABLE PROGRAM WHICH HAS A ROUTINE THAT RECEIVES A STANDARD INTERNAL TABLE.

TYPES: BEGIN OF TY_LINE_23,
         COMP1 TYPE C LENGTH 10,
         COMP2 TYPE STRING,
         COMP3 TYPE C LENGTH 5,
       END OF TY_LINE_23.

TYPES: TY_TT_LINE TYPE TABLE OF TY_LINE_23.

FORM REPLACE_SPACES CHANGING CH_ITAB TYPE TY_TT_LINE.
  DATA LWA TYPE TY_LINE_23.
  LOOP AT CH_ITAB INTO LWA.
    REPLACE ALL OCCURRENCES OF REGEX '\S' IN LWA-COMP1 WITH '_' IN CHARACTER
    MODE.
    REPLACE ALL OCCURRENCES OF REGEX '\S' IN LWA-COMP2 WITH '_' IN
    CHARACTER MODE.
    REPLACE ALL OCCURRENCES OF REGEX '\S' IN LWA-COMP3 WITH '_' IN CHARACTER
    MODE.
    MODIFY CH_ITAB INDEX SY-TABIX FROM LWA.
  ENDLOOP.
ENDFORM.

FORM PRINT_ITAB USING US_ITAB TYPE TY_TT_LINE.
  DATA LWA TYPE TY_LINE_23.
  LOOP AT US_ITAB INTO LWA.
    WRITE: LWA-COMP1 COLOR 1. NEW-LINE.
    WRITE: LWA-COMP2 COLOR 2. NEW-LINE.
    WRITE: LWA-COMP3 COLOR 3. NEW-LINE.
    WRITE /.
  ENDLOOP.
ENDFORM.

FORM TASK23.
  DATA ITAB TYPE TY_TT_LINE.
  DATA WA TYPE TY_LINE_23.

  WA-COMP1 = 'ABAP 101'.
  WA-COMP2 = 'ONE TWO THREE FOUR FIVE SIX SEVEN EIGHT NINE'.
  WA-COMP3 = '12345'.
  APPEND WA TO ITAB.
  CLEAR WA.

  WA-COMP1 = 'ABAP101'.
  WA-COMP2 = 'ONE/TWO/THREE/FOUR FIVE/SIX/SEVEN/EIGHT/NINE'.
  WA-COMP3 = '12 45'.
  APPEND WA TO ITAB.
  CLEAR WA.

  WA-COMP1 = ' '.
  WA-COMP2 ='ONE/TWO/THREE/FOUR+ =_-FIVE/SIX/SEVEN/EIGHT/NINE'.
  WA-COMP3 = ''.
  APPEND WA TO ITAB.
  CLEAR WA.

  WRITE: 'BEFORE REPLACE'. NEW-LINE.
  PERFORM PRINT_ITAB
  USING
  ITAB.

  PERFORM REPLACE_SPACES
  CHANGING
  ITAB.

  WRITE: /, 'AFTER REPLACE'. NEW-LINE.
  PERFORM PRINT_ITAB
  USING
  ITAB.
ENDFORM.

* TASK 24 WRITE AN EXECUTABLE PROGRAM WHICH HAS A ROUTINE THAT RECEIVES A STANDARD INTERNAL TABLE.

TYPES: BEGIN OF TY_EMPLOYEE_24,
         FIRST_NAME TYPE STRING,
         LAST_NAME  TYPE STRING,
         DEPARTMENT TYPE STRING,
       END OF TY_EMPLOYEE_24.

TYPES: TY_EMPLOYEE_24_TABLE TYPE STANDARD TABLE OF TY_EMPLOYEE_24 WITH DEFAULT KEY.

FORM REPLACE_SPACES_WITH_UNDERSCORE
  CHANGING CT_TABLE TYPE TY_EMPLOYEE_24_TABLE.

  FIELD-SYMBOLS: <FS_LINE> TYPE TY_EMPLOYEE_24.

  LOOP AT CT_TABLE ASSIGNING <FS_LINE>.
    IF <FS_LINE>-FIRST_NAME IS NOT INITIAL.
      REPLACE ALL OCCURRENCES OF REGEX '\S' IN <FS_LINE>-FIRST_NAME WITH '_'.
    ENDIF.

    IF <FS_LINE>-LAST_NAME IS NOT INITIAL.
      REPLACE ALL OCCURRENCES OF REGEX '\S' IN <FS_LINE>-LAST_NAME WITH '_'.
    ENDIF.

    IF <FS_LINE>-DEPARTMENT IS NOT INITIAL.
      REPLACE ALL OCCURRENCES OF REGEX '\S' IN <FS_LINE>-DEPARTMENT WITH '_'.
    ENDIF.
  ENDLOOP.
ENDFORM.

FORM DISPLAY_TABLE_CONTENTS USING IT_TABLE TYPE TY_EMPLOYEE_24_TABLE
                                  IV_TITLE TYPE STRING.

  WRITE: / IV_TITLE.
  ULINE.

  WRITE: / 'FIRST NAME'.
  WRITE: 25 'LAST NAME'.
  WRITE: 50 'DEPARTMENT'.
  ULINE.

  LOOP AT IT_TABLE INTO DATA(LS_EMPLOYEE).
    WRITE: / LS_EMPLOYEE-FIRST_NAME.
    WRITE: 25 LS_EMPLOYEE-LAST_NAME.
    WRITE: 50 LS_EMPLOYEE-DEPARTMENT.
  ENDLOOP.

  NEW-LINE.
  ULINE.
ENDFORM.

* MAIN PROGRAM EXECUTION
FORM TASK24.
  DATA: LT_EMPLOYEES TYPE TY_EMPLOYEE_24_TABLE.

  APPEND VALUE #(
    FIRST_NAME  = 'JOHN Q'
    LAST_NAME   = 'DOE Q'
    DEPARTMENT = 'Q   IT'
  ) TO LT_EMPLOYEES.

  APPEND VALUE #(
    FIRST_NAME  = ' JANE MARIE'
    LAST_NAME   = ' '
    DEPARTMENT = 'HUMAN RCES '
  ) TO LT_EMPLOYEES.

  APPEND VALUE #(
    FIRST_NAME  = 'MICHAEL DAVID'
    LAST_NAME   = 'WILLIAMS'
    DEPARTMENT = 'FINANCE'
  ) TO LT_EMPLOYEES.

  APPEND VALUE #(
    FIRST_NAME  = 'EMILY'
    LAST_NAME   = 'BROWN'
    DEPARTMENT = 'PRODUCT DEVELOPMENT'
  ) TO LT_EMPLOYEES.

  APPEND VALUE #(
    FIRST_NAME  = 'ROBERT JAMES'
    LAST_NAME   = 'MILLER THOMPSON'
    DEPARTMENT = 'CUSTOMER SUPPORT'
  ) TO LT_EMPLOYEES.

  APPEND VALUE #(
    FIRST_NAME  = 'SARAH'
    LAST_NAME   = 'DAVIS'
    DEPARTMENT = 'MARKETING'
  ) TO LT_EMPLOYEES.

  APPEND VALUE #(
    FIRST_NAME  = 'DANIEL PATRICK'
    LAST_NAME   = 'WILSON'
    DEPARTMENT = 'SALES OPERATIONS'
  ) TO LT_EMPLOYEES.

  APPEND VALUE #(
    FIRST_NAME  = 'LISA'
    LAST_NAME   = 'GARCIA RODRIGUEZ'
    DEPARTMENT = 'LEGAL'
  ) TO LT_EMPLOYEES.

  APPEND VALUE #(
    FIRST_NAME  = 'CHRISTOPHER MICHAEL'
    LAST_NAME   = 'ANDERSON PETERSON'
    DEPARTMENT = 'EXECUTIVE MANAGEMENT'
  ) TO LT_EMPLOYEES.

  APPEND VALUE #(
    FIRST_NAME  = 'ELIZABETH ANNE MARIE'
    LAST_NAME   = 'MARTINEZ RODRIGUEZ GONZALEZ'
    DEPARTMENT = 'INTERNATIONAL RELATIONS'
  ) TO LT_EMPLOYEES.

  PERFORM DISPLAY_TABLE_CONTENTS
    USING
      LT_EMPLOYEES
      'ORIGINAL TABLE CONTENTS'.

  PERFORM REPLACE_SPACES_WITH_UNDERSCORE
    CHANGING LT_EMPLOYEES.

  PERFORM DISPLAY_TABLE_CONTENTS
   USING
      LT_EMPLOYEES
      'MODIFIED TABLE CONTENTS (SPACES REPLACED)'.
ENDFORM.

* TASK 25 WRITE AN EXECUTABLE PROGRAM WHICH HAS A ROUTINE THAT RECEIVES AN INTERNAL TABLE OF STRINGS.

*&---------------------------------------------------------------------*
*& ROUTINE TO CONCATENATE STRINGS IN A SIMPLE LINEAR MANNER
*&---------------------------------------------------------------------*
FORM CONCATENATE_STRINGS
  USING
    US_T_STRINGS TYPE TABLE_OF_STRINGS
  CHANGING
    CH_CONCATENATED_STRING TYPE STRING.

  LOOP AT US_T_STRINGS ASSIGNING FIELD-SYMBOL(<STRING_LINE>).
    CONCATENATE CH_CONCATENATED_STRING <STRING_LINE>
      INTO CH_CONCATENATED_STRING.
  ENDLOOP.
ENDFORM.

*&---------------------------------------------------------------------*
*& ROUTINE TO CONCATENATE STRINGS IN MULTIPLE WAYS
*&---------------------------------------------------------------------*
FORM CONCATENATE_STRINGS_IN_WAYS
  USING
    US_T_STRINGS      TYPE TABLE_OF_STRINGS
    US_V_CONCAT_LOGIC TYPE C
  CHANGING
    CH_CONCATENATED_STRING TYPE STRING.

  DATA T_COPYED_STRINGS LIKE US_T_STRINGS.
  T_COPYED_STRINGS = US_T_STRINGS.

  CASE US_V_CONCAT_LOGIC.
    WHEN '1'.
      PERFORM CONCATENATE_STRINGS
        USING T_COPYED_STRINGS
        CHANGING CH_CONCATENATED_STRING.
    WHEN '2'.
      SORT T_COPYED_STRINGS.
      PERFORM CONCATENATE_STRINGS
        USING T_COPYED_STRINGS
        CHANGING CH_CONCATENATED_STRING.
    WHEN '3'.
      SORT T_COPYED_STRINGS DESCENDING.
      PERFORM CONCATENATE_STRINGS
        USING T_COPYED_STRINGS
        CHANGING CH_CONCATENATED_STRING.
    WHEN '4'.
      DATA VL_NUMBER_OF_STRINGS TYPE I.
      FIELD-SYMBOLS <STRING_LINE> TYPE STRING.
      DESCRIBE TABLE T_COPYED_STRINGS LINES VL_NUMBER_OF_STRINGS.

      WHILE VL_NUMBER_OF_STRINGS > 0.
        READ TABLE T_COPYED_STRINGS
          ASSIGNING <STRING_LINE>
          INDEX VL_NUMBER_OF_STRINGS.

        IF SY-SUBRC IS INITIAL.
          CONCATENATE CH_CONCATENATED_STRING <STRING_LINE>
            INTO CH_CONCATENATED_STRING.
        ENDIF.

        UNASSIGN <STRING_LINE>.
        VL_NUMBER_OF_STRINGS = VL_NUMBER_OF_STRINGS - 1.
      ENDWHILE.
  ENDCASE.
ENDFORM.

*&---------------------------------------------------------------------*
*& MAIN PROGRAM EXECUTION
*&---------------------------------------------------------------------*
FORM TASK25.
  DATA IT_STRINGS TYPE TABLE OF STRING.
  DATA GV_CONCATENATED TYPE STRING.

  APPEND 'A' TO IT_STRINGS.
  APPEND 'B' TO IT_STRINGS.
  APPEND 'C' TO IT_STRINGS.
  APPEND 'D' TO IT_STRINGS.
  APPEND 'X' TO IT_STRINGS.
  APPEND 'Y' TO IT_STRINGS.
  APPEND 'Z' TO IT_STRINGS.
  APPEND 'M' TO IT_STRINGS.
  APPEND 'N' TO IT_STRINGS.
  APPEND 'O' TO IT_STRINGS.

  PERFORM CONCATENATE_STRINGS_IN_WAYS
    USING
      IT_STRINGS
      '1'
    CHANGING
      GV_CONCATENATED.
  WRITE: '1 - ', GV_CONCATENATED, /.
  CLEAR GV_CONCATENATED.

  PERFORM CONCATENATE_STRINGS_IN_WAYS
    USING
      IT_STRINGS
      '2'
    CHANGING
      GV_CONCATENATED.
  WRITE: '2 - ', GV_CONCATENATED, /.
  CLEAR GV_CONCATENATED.

  PERFORM CONCATENATE_STRINGS_IN_WAYS
    USING
      IT_STRINGS
      '3'
    CHANGING
      GV_CONCATENATED.
  WRITE: '3 - ', GV_CONCATENATED, /.
  CLEAR GV_CONCATENATED.

  PERFORM CONCATENATE_STRINGS_IN_WAYS
    USING
      IT_STRINGS
      '4'
    CHANGING
      GV_CONCATENATED.
  WRITE: '4 - ', GV_CONCATENATED, /.
  CLEAR GV_CONCATENATED.
ENDFORM.

* TASK 26 WRITE AN EXECUTABLE PROGRAM WITH TWO PARAMETERS TYPES AS INTEGERS.

*&---------------------------------------------------------------------*
*& SELECTION SCREEN PARAMETERS
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK BT26 WITH FRAME TITLE TEXT-B26.
PARAMETERS:
  P_NUM_26 TYPE INT8,
  P_LEN_26 TYPE I.
SELECTION-SCREEN END OF BLOCK BT26.

*&---------------------------------------------------------------------*
*& ROUTINE TO FORMAT NUMBER WITH FIXED LENGTH
*&---------------------------------------------------------------------*
FORM FORMAT_NUMBER
  USING
    IV_NUMBER TYPE INT8
    IV_LENGTH TYPE I
  CHANGING
    CV_FORMATTED_NUMBER TYPE CHAR255.

  DATA:
    LV_NUMBER_STRING  TYPE STRING,
    LV_NUMBER_LENGTH  TYPE I,
    LV_PADDING_LENGTH TYPE I,
    LV_PADDED_NUMBER  TYPE STRING.

  " CONVERT NUMBER TO STRING
  LV_NUMBER_STRING = |{ IV_NUMBER }|.
  LV_NUMBER_LENGTH = STRLEN( LV_NUMBER_STRING ).

  " DETERMINE PADDING REQUIREMENTS
  IF LV_NUMBER_LENGTH > IV_LENGTH.
    " IF NUMBER IS LONGER THAN DESIRED LENGTH, TRUNCATE FROM LEFT
    DATA(LV_INDEX) = LV_NUMBER_LENGTH - IV_LENGTH.
    LV_PADDED_NUMBER = LV_NUMBER_STRING+LV_INDEX(IV_LENGTH).
  ELSE.
    " IF NUMBER IS SHORTER, PAD WITH ZEROS
    LV_PADDING_LENGTH = IV_LENGTH - LV_NUMBER_LENGTH.

    " CREATE PADDING STRING
    LV_PADDED_NUMBER =
      REPEAT( VAL = '0'
              OCC = LV_PADDING_LENGTH ) && LV_NUMBER_STRING.
  ENDIF.
  " RETURN FORMATTED NUMBER
  CV_FORMATTED_NUMBER = LV_PADDED_NUMBER.
ENDFORM.

FORM TASK26.
  IF P_NUM_26 IS INITIAL OR P_LEN_26 IS INITIAL.
    RETURN.
  ENDIF.
  PERFORM FORMAT_NUMBER
    USING P_NUM_26 P_LEN_26
    CHANGING SY-LISEL.

  WRITE: / SY-LISEL.
ENDFORM.

* TASK 27 WRITE AN EXECUTABLE PROGRAM WITH TWO PARAMETERS WHICH REPRESENTS A BASE AND EXPONENT.

*&---------------------------------------------------------------------*
*& SELECTION SCREEN PARAMETERS
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK BT27 WITH FRAME TITLE TEXT-027.
PARAMETERS: P_BASE TYPE I, P_EXP TYPE I.
SELECTION-SCREEN END OF BLOCK BT27.

*&---------------------------------------------------------------------*
*& MAIN PROGRAM EXECUTION
*&---------------------------------------------------------------------*
FORM TASK27.
  DATA: LV_RESULT TYPE I.

  IF P_BASE IS INITIAL OR P_EXP IS INITIAL.
    WRITE: / 'BOTH PARAMETERS (BASE AND EXPONENT) ARE REQUIRED!'.
    EXIT.
  ENDIF.

  LV_RESULT = P_BASE ** P_EXP.

  WRITE: / 'BASE: ', P_BASE.
  WRITE: / 'EXPONENT: ', P_EXP.
  WRITE: / 'RESULT: ', LV_RESULT.
ENDFORM.

* TAKS 28 WRITE AN EXECUTABLE PROGRAM WITH TWO PARAMETERS (A STRING AND A NUMBER) THE NUMBER.

SELECTION-SCREEN BEGIN OF BLOCK BT28 WITH FRAME TITLE TEXT-B28.
PARAMETERS: P_STR_28 TYPE STRING, P_NUM_28 TYPE I.
SELECTION-SCREEN END OF BLOCK BT28.

FORM TASK28.
  IF P_NUM_28 IS INITIAL OR P_NUM_28 > 25.
    MESSAGE 'P_NUM IS INVALID, VALID [1:25]' TYPE 'E'.
    RETURN.
  ENDIF.
  PERFORM PRINT_INCREMENTAL_STRING
    USING P_STR_28 P_NUM_28.
ENDFORM.

FORM PRINT_INCREMENTAL_STRING
USING
  IV_STRING TYPE STRING
  IV_NUMBER TYPE I.

  DATA:
    LV_CURRENT_LINE TYPE STRING,
    LV_LINE_NUMBER  TYPE I.

  DO IV_NUMBER TIMES.
    LV_LINE_NUMBER = SY-INDEX.
    LV_CURRENT_LINE = IV_STRING(LV_LINE_NUMBER).

    WRITE: / |LINE [{ LV_LINE_NUMBER }]: { LV_CURRENT_LINE }|.
  ENDDO.
ENDFORM.

* TASK 29 WRITE AN EXECUTABLE PROGRAM WHICH HAS TWO INTERNAL TABLES, WITH A HEADER LINE.
TYPES: BEGIN OF TY_TABLE_29,
         COL1 TYPE STRING,
         COL2 TYPE STRING,
       END OF TY_TABLE_29.

DATA: IT_WITH_HEADER TYPE TABLE OF TY_TABLE_29 WITH HEADER LINE.
DATA: WA_WITHOUT_HEADER TYPE TY_TABLE_29,
      IT_WITHOUT_HEADER TYPE TABLE OF TY_TABLE_29.

FORM TASK29.
  IT_WITH_HEADER-COL1 = 'RECORD 1 COL1'.
  IT_WITH_HEADER-COL2 = 'RECORD 1 COL2'.
  APPEND IT_WITH_HEADER.

  IT_WITH_HEADER-COL1 = 'RECORD 2 COL1'.
  IT_WITH_HEADER-COL2 = 'RECORD 2 COL2'.
  APPEND IT_WITH_HEADER.

  IT_WITH_HEADER-COL1 = 'RECORD 3 COL1'.
  IT_WITH_HEADER-COL2 = 'RECORD 3 COL2'.
  APPEND IT_WITH_HEADER.

  IT_WITH_HEADER-COL1 = 'RECORD 4 COL1'.
  IT_WITH_HEADER-COL2 = 'RECORD 4 COL2'.
  APPEND IT_WITH_HEADER.

  IT_WITH_HEADER-COL1 = 'RECORD 5 COL1'.
  IT_WITH_HEADER-COL2 = 'RECORD 5 COL2'.
  APPEND IT_WITH_HEADER.

  WA_WITHOUT_HEADER-COL1 = 'RECORD 1 COL1'.
  WA_WITHOUT_HEADER-COL2 = 'RECORD 1 COL2'.
  APPEND WA_WITHOUT_HEADER TO IT_WITHOUT_HEADER.

  WA_WITHOUT_HEADER-COL1 = 'RECORD 2 COL1'.
  WA_WITHOUT_HEADER-COL2 = 'RECORD 2 COL2'.
  APPEND WA_WITHOUT_HEADER TO IT_WITHOUT_HEADER.

  WA_WITHOUT_HEADER-COL1 = 'RECORD 3 COL1'.
  WA_WITHOUT_HEADER-COL2 = 'RECORD 3 COL2'.
  APPEND WA_WITHOUT_HEADER TO IT_WITHOUT_HEADER.

  WA_WITHOUT_HEADER-COL1 = 'RECORD 4 COL1'.
  WA_WITHOUT_HEADER-COL2 = 'RECORD 4 COL2'.
  APPEND WA_WITHOUT_HEADER TO IT_WITHOUT_HEADER.

  WA_WITHOUT_HEADER-COL1 = 'RECORD 5 COL1'.
  WA_WITHOUT_HEADER-COL2 = 'RECORD 5 COL2'.
  APPEND WA_WITHOUT_HEADER TO IT_WITHOUT_HEADER.

  WRITE: / 'CONTENTS OF TABLE WITH HEADER LINE:'.
  LOOP AT IT_WITH_HEADER.
    WRITE: / IT_WITH_HEADER-COL1, IT_WITH_HEADER-COL2.
  ENDLOOP.

  WRITE: / 'CONTENTS OF TABLE WITHOUT HEADER LINE:'.
  LOOP AT IT_WITHOUT_HEADER INTO WA_WITHOUT_HEADER.
    WRITE: / WA_WITHOUT_HEADER-COL1, WA_WITHOUT_HEADER-COL2.
  ENDLOOP.
ENDFORM.

* TASK 30 HAVE A ROUTINE THAT RECEIVES AN INTERNAL TABLE AND THE SORT IT BY ITS FIRST COLUMN.
TYPES: BEGIN OF TY_TABLE_30,
         COL1 TYPE STRING,
         COL2 TYPE STRING,
         COL3 TYPE STRING,
       END OF TY_TABLE_30.
TYPES: TT_TABLE_30 TYPE TABLE OF TY_TABLE_30 WITH EMPTY KEY.

DATA: IT_DATA_30 TYPE TT_TABLE_30,
      WA_DATA_30 TYPE TY_TABLE_30.

FORM SORT_TABLE_30 CHANGING CT_ANY_TABLE TYPE TT_TABLE_30.
  SORT CT_ANY_TABLE BY COL1 ASCENDING.
ENDFORM.

* MAIN PROGRAM
FORM TASK30.
  APPEND VALUE #( COL1 = 'C' COL2 = 'ROW 3 COL2' COL3 = 'ROW 3 COL3' ) TO IT_DATA_30.
  APPEND VALUE #( COL1 = 'A' COL2 = 'ROW 1 COL2' COL3 = 'ROW 1 COL3' ) TO IT_DATA_30.
  APPEND VALUE #( COL1 = 'B' COL2 = 'ROW 2 COL2' COL3 = 'ROW 2 COL3' ) TO IT_DATA_30.
  APPEND VALUE #( COL1 = 'D' COL2 = 'ROW 4 COL2' COL3 = 'ROW 4 COL3' ) TO IT_DATA_30.

  WRITE: / 'UNSORTED TABLE:'.
  LOOP AT IT_DATA_30 INTO WA_DATA_30.
    WRITE: / WA_DATA_30-COL1, WA_DATA_30-COL2, WA_DATA_30-COL3.
  ENDLOOP.

  PERFORM SORT_TABLE_30 CHANGING IT_DATA_30.

  WRITE: / 'SORTED TABLE BY COL1:'.
  LOOP AT IT_DATA_30 INTO WA_DATA_30.
    WRITE: / WA_DATA_30-COL1, WA_DATA_30-COL2, WA_DATA_30-COL3.
  ENDLOOP.
ENDFORM.

* TASK 31 HAVE A ROUTINE THAT RECEIVES AN INTERNAL TABLE (WITH AT LEAST THREE COLUMNS).
TYPES: BEGIN OF TY_TABLE_31,
         COL1 TYPE STRING,
         COL2 TYPE STRING,
         COL3 TYPE STRING,
       END OF TY_TABLE_31.

TYPES: TT_TABLE_31 TYPE STANDARD TABLE OF TY_TABLE_31 WITH EMPTY KEY.

DATA: IT_DATA_31 TYPE TT_TABLE_31,
      WA_DATA_31 TYPE TY_TABLE_31.

FORM SORT_TABLE_31 USING IV_COLUMN_NAME TYPE STRING
                CHANGING CT_ANY_TABLE   TYPE TT_TABLE_31.
  FIELD-SYMBOLS: <SORT_FIELD> TYPE ANY.

  ASSIGN COMPONENT IV_COLUMN_NAME OF STRUCTURE WA_DATA_31 TO <SORT_FIELD>.
  IF SY-SUBRC <> 0.
    WRITE: / 'INVALID COLUMN NAME:', IV_COLUMN_NAME.
    EXIT.
  ENDIF.

  SORT CT_ANY_TABLE BY (IV_COLUMN_NAME).
ENDFORM.

* MAIN PROGRAM
FORM TASK31.
  DATA: LV_COLUMN_NAME TYPE STRING.
  APPEND VALUE #( COL1 = 'C' COL2 = 'ROW 3 COL2' COL3 = 'ROW 3 COL3' ) TO IT_DATA_31.
  APPEND VALUE #( COL1 = 'A' COL2 = 'ROW 1 COL2' COL3 = 'ROW 1 COL3' ) TO IT_DATA_31.
  APPEND VALUE #( COL1 = 'B' COL2 = 'ROW 2 COL2' COL3 = 'ROW 2 COL3' ) TO IT_DATA_31.
  APPEND VALUE #( COL1 = 'D' COL2 = 'ROW 4 COL2' COL3 = 'ROW 4 COL3' ) TO IT_DATA_31.

  WRITE: / 'UNSORTED TABLE:'.
  LOOP AT IT_DATA_31 INTO WA_DATA_31.
    WRITE: / WA_DATA_31-COL1, WA_DATA_31-COL2, WA_DATA_31-COL3.
  ENDLOOP.

  LV_COLUMN_NAME = 'COL2'.
  PERFORM SORT_TABLE_31 USING LV_COLUMN_NAME CHANGING IT_DATA_31.

  WRITE: / 'SORTED TABLE BY', LV_COLUMN_NAME, ':'.
  LOOP AT IT_DATA_31 INTO WA_DATA_31.
    WRITE: / WA_DATA_31-COL1, WA_DATA_31-COL2, WA_DATA_31-COL3.
  ENDLOOP.
ENDFORM.

* TASK 32 HAVE A ROUTINE THAT RECEIVES AN INTERNAL TABLE (WITH AT LEAST THREE COLUMNS).
TYPES: BEGIN OF TY_TABLE_32,
         COL1 TYPE STRING,
         COL2 TYPE STRING,
         COL3 TYPE STRING,
       END OF TY_TABLE_32.
TYPES: TT_TABLE_32 TYPE STANDARD TABLE OF TY_TABLE_32 WITH EMPTY KEY.

TYPES: BEGIN OF TY_SORT_COLUMNS_32,
         COLUMN_NAME TYPE STRING,
       END OF TY_SORT_COLUMNS_32.
TYPES: TT_SORT_COLUMNS_32 TYPE STANDARD TABLE OF TY_SORT_COLUMNS_32 WITH EMPTY KEY.

DATA: IT_DATA_32      TYPE TT_TABLE_32,
      WA_DATA_32      TYPE TY_TABLE_32,
      IT_SORT_COLUMNS TYPE TT_SORT_COLUMNS_32,
      WA_SORT_COLUMN  TYPE TY_SORT_COLUMNS_32.


FORM SORT_TABLE_DYNAMIC USING IT_SORT_COLUMNS TYPE TT_SORT_COLUMNS_32
                        CHANGING CT_ANY_TABLE TYPE TT_TABLE_32.

  FIELD-SYMBOLS: <SORT_FIELD> TYPE ANY.
  DATA(SORT_TAB) = VALUE ABAP_SORTORDER_TAB( ).

  LOOP AT IT_SORT_COLUMNS INTO WA_SORT_COLUMN.
    " CHECK IF THE COLUMN EXISTS IN THE STRUCTURE
    ASSIGN COMPONENT WA_SORT_COLUMN-COLUMN_NAME OF STRUCTURE WA_DATA_32 TO <SORT_FIELD>.
    IF SY-SUBRC <> 0.
      WRITE: / 'INVALID COLUMN NAME:', WA_SORT_COLUMN-COLUMN_NAME.
      EXIT.
    ENDIF.

    APPEND VALUE ABAP_SORTORDER( NAME = WA_SORT_COLUMN-COLUMN_NAME ) TO SORT_TAB.
  ENDLOOP.

  IF SORT_TAB IS NOT INITIAL.
    SORT CT_ANY_TABLE BY (SORT_TAB).
  ELSE.
    WRITE: / 'NO VALID COLUMNS PROVIDED FOR SORTING.'.
  ENDIF.
ENDFORM.

* MAIN PROGRAM
FORM TASK32.
  APPEND VALUE #( COL1 = 'C' COL2 = 'ROW 3 COL2' COL3 = '3' ) TO IT_DATA_32.
  APPEND VALUE #( COL1 = 'A' COL2 = 'ROW 1 COL2' COL3 = '2' ) TO IT_DATA_32.
  APPEND VALUE #( COL1 = 'B' COL2 = 'ROW 2 COL2' COL3 = '1' ) TO IT_DATA_32.
  APPEND VALUE #( COL1 = 'A' COL2 = 'ROW 4 COL2' COL3 = '3' ) TO IT_DATA_32.

  APPEND VALUE #( COLUMN_NAME = 'COL1' ) TO IT_SORT_COLUMNS.
  APPEND VALUE #( COLUMN_NAME = 'COL3' ) TO IT_SORT_COLUMNS.

  WRITE: / 'UNSORTED TABLE:'.
  LOOP AT IT_DATA_32 INTO WA_DATA_32.
    WRITE: / WA_DATA_32-COL1, WA_DATA_32-COL2, WA_DATA_32-COL3.
  ENDLOOP.

  PERFORM SORT_TABLE_DYNAMIC USING IT_SORT_COLUMNS CHANGING IT_DATA_32.

  WRITE: / 'SORTED TABLE BY SPECIFIED COLUMNS:'.
  LOOP AT IT_DATA_32 INTO WA_DATA_32.
    WRITE: / WA_DATA_32-COL1, WA_DATA_32-COL2, WA_DATA_32-COL3.
  ENDLOOP.
ENDFORM.

START-OF-SELECTION.
  PERFORM TASK1.
  PERFORM TASK2.
  PERFORM TASK3 USING P_NUM1 P_NUM2.
  PERFORM TASK4.
  PERFORM TASK5.
  PERFORM TASK6.
  PERFORM TASK7.
  PERFORM TASK8.
  PERFORM TASK9.
  PERFORM TASK10.
  PERFORM TASK11.
  PERFORM TASK12.
  PERFORM TASK13.
  PERFORM TASK14.
  PERFORM TASK15.
  PERFORM TASK16.
  PERFORM TASK17.
  PERFORM TASK18.
  PERFORM TASK19.
  PERFORM TASK20.
  PERFORM TASK21.
  PERFORM TASK22.
  PERFORM TASK23.
  PERFORM TASK24.
  PERFORM TASK25.
  PERFORM TASK26.
  PERFORM TASK27.
  PERFORM TASK28.
  PERFORM TASK29.
  PERFORM TASK30.
  PERFORM TASK31.
  PERFORM TASK32.