*&---------------------------------------------------------------------*
*& Report ZSYR1412_T1_OOP_NAMDV
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZSYR1412_T1_OOP_NAMDV.

* DEFINITION CLASS NUM PROCESSOR
CLASS ZCL_NUM_PROCESSOR DEFINITION.
  PUBLIC SECTION.
    METHODS: CONSTRUCTOR IMPORTING LV_NUM1 TYPE I
                                   LV_NUM2 TYPE I,
             COMPARE_NUMBERS,
             CALCULATE_RESULT.

  PRIVATE SECTION.
    DATA: PV_NUM1 TYPE I,
          PV_NUM2 TYPE I.
ENDCLASS.

* IMPLEMENTATION CLASS NUM PROCESSOR
CLASS ZCL_NUM_PROCESSOR IMPLEMENTATION.
  METHOD CONSTRUCTOR.
    PV_NUM1 = LV_NUM1.
    PV_NUM2 = LV_NUM2.
  ENDMETHOD.

  METHOD COMPARE_NUMBERS.
    IF PV_NUM1 > PV_NUM2.
      WRITE: / |{ PV_NUM1 } > { PV_NUM2 }|.
    ELSEIF PV_NUM1 < PV_NUM2.
      WRITE: / |{ PV_NUM1 } < { PV_NUM2 }|.
    ELSE.
      WRITE: / |{ PV_NUM1 } = { PV_NUM2 }|.
    ENDIF.
  ENDMETHOD.

  METHOD CALCULATE_RESULT.
    DATA: LV_RESULT TYPE I.
    LV_RESULT = PV_NUM2 * ( PV_NUM1 + PV_NUM1 * PV_NUM2 ).
    WRITE: / 'RESULT:', LV_RESULT.
  ENDMETHOD.
ENDCLASS.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
PARAMETERS: P_NUM01 TYPE N OBLIGATORY,
            P_NUM02 TYPE N OBLIGATORY.
SELECTION-SCREEN END OF BLOCK B1.

START-OF-SELECTION.
  DATA: GO_NUM_PROCESSOR TYPE REF TO ZCL_NUM_PROCESSOR.

  CREATE OBJECT GO_NUM_PROCESSOR
    EXPORTING
      LV_NUM1 = CONV I( P_NUM01 )
      LV_NUM2 = CONV I( P_NUM02 ).

  GO_NUM_PROCESSOR->COMPARE_NUMBERS( ).
  GO_NUM_PROCESSOR->CALCULATE_RESULT( ).