*&---------------------------------------------------------------------*
*& Report ZSYR1450_NAMDV
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZSYR1450_NAMDV.

* 1: DECLARE A TYPE AS A CHARACTER WITH 10 POSITIONS.
TYPES: GTT_CHAR1 TYPE C LENGTH 10.

* 2: DECLARE AN INTEGER.
DATA: GV_INTEGER2 TYPE I.

* 3: DECLARE A TYPE AS A NUMBER WITH 7 POSITIONS.
TYPES: GTT_NUM3 TYPE N LENGTH 7.

* 4: DECLARE A DATE TYPE.
DATA: GV_DATE4 TYPE D.

* 5: DECLARE A TIME TYPE.
DATA: GV_TIME5 TYPE T.

* 6: DECLARE A STRUCTURE TYPE WITH 5 FIELDS OF SPECIFIED TYPES.
TYPES: BEGIN OF GTT_STRUCT6,
         FIELD1 TYPE GTT_CHAR1,
         FIELD2 TYPE I,
         FIELD3 TYPE GTT_NUM3,
         FIELD4 TYPE D,
         FIELD5 TYPE T,
       END OF GTT_STRUCT6.

* 7: DECLARE A TYPE USING THE GLOBAL STRUCTURE SFLIGHT.
TYPES: GTT_SFLIGHT7 TYPE SFLIGHT.

* 8: DECLARE A STRUCTURE TYPE WITH SPECIFIC COMPONENTS OF SFLIGHT.
TYPES: BEGIN OF GTT_SFLIGHT_PARTIAL8,
         CARRID    TYPE SFLIGHT-CARRID,
         CONNID    TYPE SFLIGHT-CONNID,
         FLDATE    TYPE SFLIGHT-FLDATE,
         PRICE     TYPE SFLIGHT-PRICE,
         CURRENCY  TYPE SFLIGHT-CURRENCY,
         PLANETYPE TYPE SFLIGHT-PLANETYPE,
         SEATSMAX  TYPE SFLIGHT-SEATSMAX,
         SEATSOCC  TYPE SFLIGHT-SEATSOCC,
       END OF GTT_SFLIGHT_PARTIAL8.

* 9: DECLARE A STRUCTURE TYPE WITH SPECIFIC COMPONENTS OF SBOOK.
TYPES: BEGIN OF GTT_SBOOK_PARTIAL9,
         CARRID   TYPE SBOOK-CARRID,
         CONNID   TYPE SBOOK-CONNID,
         FLDATE   TYPE SBOOK-FLDATE,
         BOOKID   TYPE SBOOK-BOOKID,
         CUSTOMID TYPE SBOOK-CUSTOMID,
       END OF GTT_SBOOK_PARTIAL9.

* 10: DECLARE A STRUCTURE CONTAINING ALL FIELDS.
TYPES: BEGIN OF GTT_COMBINED_STRUCT10,
         BOOKID   TYPE SBOOK-BOOKID,
         CUSTOMID TYPE SBOOK-CUSTOMID,
         INCLUDE  TYPE GTT_SFLIGHT_PARTIAL8.
TYPES: END OF GTT_COMBINED_STRUCT10.

DATA: GV_COMBINED_STRUCT TYPE GTT_COMBINED_STRUCT10.

* 11: DECLARE A TABLE TYPE OF INTEGERS.
TYPES: GTT_INT_TABLE11 TYPE TABLE OF I.

* 12: DECLARE A TABLE TYPE WITH ALL COMPONENTS OF SFLIGHT.
TYPES: GTT_SFLIGHT_TABLE TYPE TABLE OF SFLIGHT.

* 13: DECLARE A TABLE TYPE USING THE STRUCTURE.
TYPES: GTT_SFLIGHT_PARTIAL_TABLE TYPE TABLE OF GTT_SFLIGHT_PARTIAL8.

* 14: DECLARE A TABLE TYPE WITH SPECIFIC FIELDS OF SBOOK AND CUSTOMID AS PART OF THE KEY.
TYPES: GTT_SBOOK_KEYED_TABLE14 TYPE TABLE OF GTT_SBOOK_PARTIAL9
                               WITH KEY CARRID CONNID FLDATE CUSTOMID.

* 15: DECLARE A CHARACTER VARIABLE WITH 10 POSITIONS.
DATA: GV_HELLO15 TYPE GTT_CHAR1 VALUE 'HELLO SAP'.

* 16: DECLARE A NUMERIC VARIABLE WITH 4 POSITIONS.
DATA: GV_NUMERIC16 TYPE N LENGTH 4 VALUE '1616'.

* 17: DECLARE AN INTEGER VARIABLE.
DATA: GV_INT17 TYPE I VALUE 17.

* 18: DECLARE AN INTEGER VARIABLE.
DATA: V_INT18 TYPE I VALUE 18.

* 19: DECLARE A DATE VARIABLE WITH HALLOWEEN DAY.
DATA: GV_HALLOWEEN19 TYPE D VALUE '20231031'.

* 20: DECLARE A PACKED NUMBER VARIABLE WITH 7 DECIMAL PLACES.
DATA: GV_PACKED20 TYPE P DECIMALS 7.

* 21: DECLARE A VARIABLE OF TYPE S_CARR_ID.
DATA: GV_S_CARR_ID21 TYPE S_CARR_ID.

* 22: DECLARE A VARIABLE OF THE SAME TYPE AS FIELD CARRID FROM TABLE SPFLI.
DATA: GV_CARRID22 TYPE SPFLI-CARRID.

* 23: DECLARE A VARIABLE OF THE SAME TYPE AS FIELD FLDATE FROM SFLIGHT.
DATA: GV_FLDATE23 TYPE SFLIGHT-FLDATE.

* 24: DECLARE A STRUCTURE OF THE SAME TYPE AS SBOOK.
DATA: GV_SBOOK_STRUCT24 TYPE SBOOK.

* 25: DECLARE A STRUCTURE WITH SPECIFIC FIELDS OF SFLIGHT.
DATA: BEGIN OF GTT_SFLIGHT_FIELDS25,
        CARRID    TYPE SFLIGHT-CARRID,
        CONNID    TYPE SFLIGHT-CONNID,
        FLDATE    TYPE SFLIGHT-FLDATE,
        PRICE     TYPE SFLIGHT-PRICE,
        CURRENCY  TYPE SFLIGHT-CURRENCY,
        PLANETYPE TYPE SFLIGHT-PLANETYPE,
        SEATSMAX  TYPE SFLIGHT-SEATSMAX,
        SEATSOCC  TYPE SFLIGHT-SEATSOCC,
      END OF GTT_SFLIGHT_FIELDS25.

* 26: DECLARE A STRUCTURE WITH ALL FIELDS OF SBOOK.
DATA: BEGIN OF GTT_SBOOK_SCUST_FIELDS26,
        INCLUDE   TYPE SBOOK,
        TELEPHONE TYPE SCUSTOM-TELEPHONE,
      END OF GTT_SBOOK_SCUST_FIELDS26.

* 27: DECLARE AN INTERNAL TABLE WITH SPECIFIC FIELDS OF SBOOK.
DATA: GT_SBOOK_TABLE27 TYPE TABLE OF GTT_SBOOK_PARTIAL9.

* 28: DECLARE AN INTERNAL TABLE WITH ALL FIELDS OF SCARR.
DATA: GT_SCARR_TABLE28 TYPE TABLE OF SCARR.

* 29: DECLARE AN INTERNAL TABLE WITH ALL FIELDS OF SPFLI.
DATA: GT_SPFLI_TABLE29 TYPE TABLE OF SPFLI.

* 30: DECLARE AN INTERNAL TABLE WITH FIELDS OF SCARR.
DATA: BEGIN OF GTT_SCARR_SCUST_TABLE30 OCCURS 0,
        INCLUDE   TYPE SCARR,
        TELEPHONE TYPE SCUSTOM-TELEPHONE,
      END OF GTT_SCARR_SCUST_TABLE30.

* 31: DECLARE A CONSTANT CONTAINING NAME.
CONSTANTS: C_MY_NAME31 TYPE C LENGTH 50 VALUE 'NAME'.

* 32: DECLARE CONSTANTS FOR 'X' (TRUE) AND ' ' (FALSE).
CONSTANTS: C_TRUE32  TYPE C LENGTH 1 VALUE 'X',
           C_FALSE32 TYPE C LENGTH 1 VALUE ' '.

* 33: DECLARE A CONSTANT CONTAINING THE FIRST 5 DECIMALS OF PI.
CONSTANTS: C_PI33 TYPE P DECIMALS 5 VALUE '3.14159'.

* 34: DECLARE A WORK AREA OF CONSTANTS WITH INTEGER COMPONENTS.
DATA: BEGIN OF WA_CONSTANTS34,
        CONST1 TYPE I VALUE 1,
        CONST2 TYPE I VALUE 2,
        CONST3 TYPE I VALUE 3,
        CONST4 TYPE I VALUE 4,
        CONST5 TYPE I VALUE 5,
      END OF WA_CONSTANTS34.

* 35: DECLARE A WORK AREA OF 5 CONSTANT COMPONENTS.
DATA: BEGIN OF WA_MIXED_CONSTANTS35,
        CONST_CHAR   TYPE C LENGTH 10 VALUE 'CONST',
        CONST_NUM    TYPE N LENGTH 7 VALUE '1234567',
        CONST_DATE   TYPE D VALUE '20250101',
        CONST_TIME   TYPE T VALUE '123456',
        CONST_PACKED TYPE P DECIMALS 2 VALUE '12.34',
      END OF WA_MIXED_CONSTANTS35.

* 37: DECLARE ALL TYPES AND CONSTANTS FROM TYPE-POOLS ABAP AND ICON.
TYPE-POOLS: ABAP, ICON.

* 38: DECLARE A CONSTANT WITH THE SAME TYPE AS ANOTHER CONSTANT.
CONSTANTS: C_PI_COPY38 TYPE P DECIMALS 5 VALUE C_PI33.

* 39: DECLARE A TYPE USED IN OTHER CONSTRUCTS.
TYPES: GTT_COMMON39 TYPE C LENGTH 20.
DATA: GV_COMMON39   TYPE GTT_COMMON39,
      WA_COMMON39   TYPE GTT_COMMON39,
      GT_COMMON39   TYPE TABLE OF GTT_COMMON39,
      GC_COMMON39   TYPE GTT_COMMON39 VALUE 'COMMON'.

* 40: DECLARE A VARIABLE USED IN OTHER CONSTRUCTS.
DATA: GV_REUSABLE TYPE C LENGTH 20.
TYPES: GTT_REUSABLE TYPE C LENGTH 20.
DATA: WA_REUSABLE TYPE GTT_REUSABLE.
DATA: GT_REUSABLE TYPE TABLE OF GTT_REUSABLE.
CONSTANTS: C_REUSABLE TYPE GTT_REUSABLE VALUE '123'.